In [21]:
import pandas as pd

df=pd.read_csv('bad-data2.csv')
print(df.to_string())

    Steps           Day HeartRate  PeakRate  Energy
0    5000  '2024/01/01'        80       120   250.5
1    5200  '2024/01/02'        85       130   270.8
2    4800  '2024/01/03'        78       125   230.0
3    4500  '2024/01/04'        82       140   220.4
4    4600  '2024/01/05'        88       145   260.0
5    4900  '2024/01/06'        76       110   200.0
6    5100  '2024/01/07'        84       122   245.0
7   30000  '2024/01/08'        79       121   180.3
8    3000  '2024/01/09'        81       118   150.1
9    5300  '2024/01/10'        75       108   190.0
10   5000  '2024/01/11'        80       135   225.3
11   5100  '2024/01/12'        82       115   200.7
12   5100  '2024/01/12'        82       115   200.7
13   5200  '2024/01/13'        86       119   210.3
14   4800  '2024/01/14'        79       121   250.3
15   4600  '2024/01/15'        74       109   175.0
16   4700  '2024/01/16'        77       113   160.2
17   5100  '2024/01/17'        83       116   190.0
18   4000  '2024/01/18'        70       105     NaN
19   5000  '2024/01/19'        79       112   220.0
20   4500  '2024/01/20'        75       120   180.0
21   5200  '2024/01/21'        84       125   230.2
22   4800           NaN      '77'       114   210.0
23   5300  '2024/01/23'        95       100   195.0
24   4600  '2024/01/24'        82       127   175.0
25   4900  '2024/01/25'        78       122   230.5
26   4700  '2024/01/26'        80       118   190.0
27   5000  '2024/01/27'        72       110   180.0
28   5100  '2024/01/28'        81       130     NaN
29   5000  '2024/01/29'        79       128   195.0
30   5200  '2024/01/30'        76       126   250.3
31   5300  '2024/01/31'        73       102   185.0

In [23]:
#print(df.duplicated())

df = df.drop_duplicates()
print(df.to_string())

    Steps           Day HeartRate  PeakRate  Energy
0    5000  '2024/01/01'        80       120   250.5
1    5200  '2024/01/02'        85       130   270.8
2    4800  '2024/01/03'        78       125   230.0
3    4500  '2024/01/04'        82       140   220.4
4    4600  '2024/01/05'        88       145   260.0
5    4900  '2024/01/06'        76       110   200.0
6    5100  '2024/01/07'        84       122   245.0
7   30000  '2024/01/08'        79       121   180.3
8    3000  '2024/01/09'        81       118   150.1
9    5300  '2024/01/10'        75       108   190.0
10   5000  '2024/01/11'        80       135   225.3
11   5100  '2024/01/12'        82       115   200.7
13   5200  '2024/01/13'        86       119   210.3
14   4800  '2024/01/14'        79       121   250.3
15   4600  '2024/01/15'        74       109   175.0
16   4700  '2024/01/16'        77       113   160.2
17   5100  '2024/01/17'        83       116   190.0
18   4000  '2024/01/18'        70       105     NaN
19   5000  '2024/01/19'        79       112   220.0
20   4500  '2024/01/20'        75       120   180.0
21   5200  '2024/01/21'        84       125   230.2
22   4800           NaN      '77'       114   210.0
23   5300  '2024/01/23'        95       100   195.0
24   4600  '2024/01/24'        82       127   175.0
25   4900  '2024/01/25'        78       122   230.5
26   4700  '2024/01/26'        80       118   190.0
27   5000  '2024/01/27'        72       110   180.0
28   5100  '2024/01/28'        81       130     NaN
29   5000  '2024/01/29'        79       128   195.0
30   5200  '2024/01/30'        76       126   250.3
31   5300  '2024/01/31'        73       102   185.0

In [24]:

x = df["Energy"].median()
df["Energy"].fillna(x, inplace=True)  # Fill missing Energy with median

print(df.to_string())

    Steps           Day HeartRate  PeakRate  Energy
0    5000  '2024/01/01'        80       120   250.5
1    5200  '2024/01/02'        85       130   270.8
2    4800  '2024/01/03'        78       125   230.0
3    4500  '2024/01/04'        82       140   220.4
4    4600  '2024/01/05'        88       145   260.0
5    4900  '2024/01/06'        76       110   200.0
6    5100  '2024/01/07'        84       122   245.0
7   30000  '2024/01/08'        79       121   180.3
8    3000  '2024/01/09'        81       118   150.1
9    5300  '2024/01/10'        75       108   190.0
10   5000  '2024/01/11'        80       135   225.3
11   5100  '2024/01/12'        82       115   200.7
13   5200  '2024/01/13'        86       119   210.3
14   4800  '2024/01/14'        79       121   250.3
15   4600  '2024/01/15'        74       109   175.0
16   4700  '2024/01/16'        77       113   160.2
17   5100  '2024/01/17'        83       116   190.0
18   4000  '2024/01/18'        70       105   200.7
19   5000  '2024/01/19'        79       112   220.0
20   4500  '2024/01/20'        75       120   180.0
21   5200  '2024/01/21'        84       125   230.2
22   4800           NaN      '77'       114   210.0
23   5300  '2024/01/23'        95       100   195.0
24   4600  '2024/01/24'        82       127   175.0
25   4900  '2024/01/25'        78       122   230.5
26   4700  '2024/01/26'        80       118   190.0
27   5000  '2024/01/27'        72       110   180.0
28   5100  '2024/01/28'        81       130   200.7
29   5000  '2024/01/29'        79       128   195.0
30   5200  '2024/01/30'        76       126   250.3
31   5300  '2024/01/31'        73       102   185.0

C:\Users\shiva\AppData\Local\Temp\ipykernel_12408\1228362738.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Energy"].fillna(x, inplace=True)  # Fill missing Energy with median

In [25]:
df.loc[7, 'Steps']=5000
print(df.to_string())

    Steps           Day HeartRate  PeakRate  Energy
0    5000  '2024/01/01'        80       120   250.5
1    5200  '2024/01/02'        85       130   270.8
2    4800  '2024/01/03'        78       125   230.0
3    4500  '2024/01/04'        82       140   220.4
4    4600  '2024/01/05'        88       145   260.0
5    4900  '2024/01/06'        76       110   200.0
6    5100  '2024/01/07'        84       122   245.0
7    5000  '2024/01/08'        79       121   180.3
8    3000  '2024/01/09'        81       118   150.1
9    5300  '2024/01/10'        75       108   190.0
10   5000  '2024/01/11'        80       135   225.3
11   5100  '2024/01/12'        82       115   200.7
13   5200  '2024/01/13'        86       119   210.3
14   4800  '2024/01/14'        79       121   250.3
15   4600  '2024/01/15'        74       109   175.0
16   4700  '2024/01/16'        77       113   160.2
17   5100  '2024/01/17'        83       116   190.0
18   4000  '2024/01/18'        70       105   200.7
19   5000  '2024/01/19'        79       112   220.0
20   4500  '2024/01/20'        75       120   180.0
21   5200  '2024/01/21'        84       125   230.2
22   4800           NaN      '77'       114   210.0
23   5300  '2024/01/23'        95       100   195.0
24   4600  '2024/01/24'        82       127   175.0
25   4900  '2024/01/25'        78       122   230.5
26   4700  '2024/01/26'        80       118   190.0
27   5000  '2024/01/27'        72       110   180.0
28   5100  '2024/01/28'        81       130   200.7
29   5000  '2024/01/29'        79       128   195.0
30   5200  '2024/01/30'        76       126   250.3
31   5300  '2024/01/31'        73       102   185.0

In [26]:
df.dropna(inplace = True)
print(df.to_string())

    Steps           Day HeartRate  PeakRate  Energy
0    5000  '2024/01/01'        80       120   250.5
1    5200  '2024/01/02'        85       130   270.8
2    4800  '2024/01/03'        78       125   230.0
3    4500  '2024/01/04'        82       140   220.4
4    4600  '2024/01/05'        88       145   260.0
5    4900  '2024/01/06'        76       110   200.0
6    5100  '2024/01/07'        84       122   245.0
7    5000  '2024/01/08'        79       121   180.3
8    3000  '2024/01/09'        81       118   150.1
9    5300  '2024/01/10'        75       108   190.0
10   5000  '2024/01/11'        80       135   225.3
11   5100  '2024/01/12'        82       115   200.7
13   5200  '2024/01/13'        86       119   210.3
14   4800  '2024/01/14'        79       121   250.3
15   4600  '2024/01/15'        74       109   175.0
16   4700  '2024/01/16'        77       113   160.2
17   5100  '2024/01/17'        83       116   190.0
18   4000  '2024/01/18'        70       105   200.7
19   5000  '2024/01/19'        79       112   220.0
20   4500  '2024/01/20'        75       120   180.0
21   5200  '2024/01/21'        84       125   230.2
23   5300  '2024/01/23'        95       100   195.0
24   4600  '2024/01/24'        82       127   175.0
25   4900  '2024/01/25'        78       122   230.5
26   4700  '2024/01/26'        80       118   190.0
27   5000  '2024/01/27'        72       110   180.0
28   5100  '2024/01/28'        81       130   200.7
29   5000  '2024/01/29'        79       128   195.0
30   5200  '2024/01/30'        76       126   250.3
31   5300  '2024/01/31'        73       102   185.0